"""This program builds a list of five-letter words by extracting
five-letter words from a text file. This program also contains the
following lists and sets that may be imported into other Python
programs:

1. ALL_LETTERS_LIST - a list of all letters in the English language in
  alphabetical order.
2. ALL_LETTERS_SET - same content as ALL_LETTERS_LIST stored in a set
   instead of a list.
3. SECRET_WORDS_LIST - a list of words in alphabetical order from which
   play.py will choose the secret word.
4. SECRET_WORDS_SET - same content as SECRET_WORDS_LIST stored in a set
   instead of a list.
5. ALLOWED_WORDS_SET - a set of the words that a user is allowed to
   enter when playing play.py.
"""
import re

# A list of all the letters in the English alphabet.
ALL_LETTERS_LIST = [
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
    "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
]

ALL_LETTERS_SET = set(ALL_LETTERS_LIST)

# A set of five letter English words.
SECRET_WORDS_SET = {
    "aback", "abase", "abate", "abbey", "abbot",
    "abhor", "abide", "abled", "abode", "abort",
    "about", "above", "abuse", "abyss", "acorn",
    "acrid", "actor", "acuse", "acute", "adage",
    "adapt", "adder", "adept", "admin", "admit",
    "adobe", "adopt", "adore", "adorn", "adult",
    "affix", "afire", "afoot", "afoul", "after",
    "again", "agape", "agate", "agent", "agile",
    "aging", "aglow", "agony", "agree", "ahead",
    "aider", "aisle", "alarm", "album", "alert",
    "algae", "alibi", "alien", "align", "alike",
    "alive", "allay", "alley", "allot", "allow",
    "alloy", "aloft", "alone", "along", "aloof",
    "aloud", "alpha", "altar", "alter", "amass",
    "amaze", "amber", "amble", "amend", "amiss",
    "amity", "among", "ample", "amply", "amuse",
    "angel", "anger", "angle", "angry", "angst",
    "anime", "ankle", "annex", "annoy", "annul",
    "annum", "anode", "antic", "anvil", "aorta",
    "apart", "aphid", "aping", "apnea", "apple",
    "apply", "apron", "aptly", "arbor", "ardor",
    "arena", "argon", "argue", "arise", "armor",
    "aroma", "arose", "array", "arrow", "arson",
    "artsy", "ascot", "ashen", "aside", "askew",
    "assay", "asset", "aster", "atlas", "atoll",
    "atone", "attic", "audio", "audit", "aught",
    "augur", "aunty", "avail", "avert", "avian",
    "avoid", "await", "awake", "award", "aware",
    "awash", "awful", "awoke", "axial", "axiom",
    "axion", "azure", "bacon", "badge", "badly",
    "bagel", "baggy", "baker", "baler", "balmy",
    "banal", "banjo", "barge", "baron", "basal",
    "bases", "basic", "basil", "basin", "basis",
    "baste", "batch", "bathe", "baton", "batty",
    "bawdy", "bayou", "beach", "beady", "beard",
    "beast", "beech", "beefy", "befit", "began",
    "begat", "beget", "begin", "begun", "being",
    "belch", "belie", "belle", "belly", "below",
    "bench", "beret", "berry", "berth", "beset",
    "besom", "betel", "bevel", "bezel", "bible",
    "bicep", "biddy", "bigot", "bilge", "billy",
    "binge", "bingo", "biome", "birch", "birth",
    "bison", "bitty", "black", "blade", "blame",
    "bland", "blank", "blare", "blast", "blaze",
    "bleak", "bleat", "bleed", "bleep", "blend",
    "bless", "blimp", "blind", "blink", "bliss",
    "blitz", "bloat", "block", "bloke", "blond",
    "blood", "bloom", "bluer", "bluff", "blunt",
    "blurb", "blurt", "blush", "board", "boast",
    "bobby", "boney", "bongo", "bonus", "booby",
    "boost", "booth", "booty", "booze", "boozy",
    "borax", "borne", "boron", "bosom", "bossy",
    "botch", "bough", "boule", "bound", "bowel",
    "boxer", "brace", "braid", "brain", "brake",
    "brand", "brash", "brass", "brave", "bravo",
    "brawl", "brawn", "bread", "break", "breed",
    "briar", "bribe", "brick", "bride", "brief",
    "brine", "bring", "brink", "briny", "brisk",
    "broad", "broil", "broke", "brood", "brook",
    "broom", "broth", "brown", "brunt", "brush",
    "brute", "buddy", "budge", "buggy", "bugle",
    "build", "built", "bulge", "bulky", "bully",
    "bunch", "bunny", "burly", "burnt", "burro",
    "burst", "bused", "bushy", "butch", "butte",
    "buxom", "buyer", "bylaw", "cabal", "cabby",
    "cabin", "cable", "cacao", "cache", "cacti",
    "caddy", "cadet", "cagey", "cairn", "camel",
    "cameo", "canal", "candy", "canny", "canoe",
    "canon", "caper", "caput", "carat", "caret",
    "cargo", "carol", "carry", "carve", "caste",
    "catch", "cater", "catty", "caulk", "cause",
    "cavil", "cease", "cedar", "cello", "chafe",
    "chaff", "chain", "chair", "chalk", "champ",
    "chant", "chaos", "chard", "charm", "chart",
    "chase", "chasm", "cheap", "cheat", "check",
    "cheek", "cheer", "chess", "chest", "chick",
    "chide", "chief", "child", "chili", "chill",
    "chime", "chirp", "chock", "choir", "choke",
    "chord", "chore", "chose", "chuck", "chump",
    "chunk", "churn", "chute", "cider", "cigar",
    "cinch", "circa", "civic", "civil", "clack",
    "claim", "clamp", "clang", "clank", "clash",
    "clasp", "class", "clave", "clean", "clear",
    "cleat", "cleft", "clerk", "click", "cliff",
    "climb", "cling", "clink", "cloak", "clock",
    "clone", "close", "cloth", "cloud", "clout",
    "clove", "clown", "cluck", "clued", "clump",
    "clung", "coach", "coast", "cobra", "cocoa",
    "colon", "color", "comet", "comfy", "comic",
    "comma", "conch", "condo", "conic", "copse",
    "coral", "corer", "corny", "corps", "couch",
    "cough", "could", "count", "coupe", "court",
    "coven", "cover", "covet", "covey", "cower",
    "coyly", "crack", "craft", "cramp", "crane",
    "crank", "crash", "crass", "crate", "crave",
    "crawl", "craze", "crazy", "creak", "cream",
    "credo", "creed", "creek", "creep", "creme",
    "crepe", "crept", "cress", "crest", "crick",
    "cried", "crier", "crime", "crimp", "crisp",
    "croak", "crock", "crone", "crony", "crook",
    "cross", "croup", "crowd", "crown", "crude",
    "cruel", "crumb", "crump", "crush", "crust",
    "crypt", "cubic", "cubit", "cumin", "curio",
    "curly", "curry", "curse", "curve", "curvy",
    "cutie", "cyber", "cycle", "cynic", "daddy",
    "daily", "dairy", "daisy", "dally", "dance",
    "dandy", "datum", "daunt", "dealt", "death",
    "debar", "debit", "debug", "debut", "decal",
    "decay", "decor", "decoy", "decry", "defer",
    "deign", "deity", "delay", "delta", "delve",
    "demon", "demur", "denim", "dense", "depot",
    "depth", "derby", "deter", "detox", "deuce",
    "devil", "dewar", "diary", "dicey", "digit",
    "dilly", "dimly", "diner", "dingo", "dingy",
    "diode", "dirge", "dirty", "disco", "ditch",
    "ditto", "ditty", "diver", "dizzy", "dodge",
    "dodgy", "doggy", "dogma", "doing", "dolly",
    "donor", "donut", "dopey", "doubt", "dough",
    "dowdy", "dowel", "downy", "dowry", "dozen",
    "draft", "drain", "drake", "drama", "drank",
    "drape", "drawl", "drawn", "dread", "dream",
    "dress", "dried", "drier", "drift", "drill",
    "drink", "drive", "droit", "droll", "drone",
    "drool", "droop", "dross", "drove", "drown",
    "druid", "drunk", "dryer", "dryly", "duchy",
    "dully", "dummy", "dumpy", "dunce", "dusky",
    "dusty", "dutch", "duvet", "dwarf", "dwell",
    "dwelt", "dying", "eager", "eagle", "early",
    "earth", "easel", "eaten", "eater", "ebony",
    "ebrua", "eclat", "edict", "edify", "eerie",
    "egret", "eight", "eject", "eking", "elate",
    "elbow", "elder", "elect", "elegy", "elfin",
    "elide", "elite", "elope", "elude", "email",
    "embed", "ember", "emcee", "empty", "enact",
    "endow", "enema", "enemy", "enjoy", "ennui",
    "ensue", "enter", "entry", "envoy", "epoch",
    "epoxy", "equal", "equip", "erase", "erect",
    "erode", "error", "erupt", "essay", "ester",
    "ether", "ethic", "ethos", "etude", "evade",
    "event", "every", "evict", "evoke", "exact",
    "exalt", "excel", "exert", "exile", "exist",
    "expel", "extol", "extra", "exult", "eying",
    "fable", "facet", "faint", "fairy", "faith",
    "false", "fancy", "fanny", "farce", "fatal",
    "fatty", "fault", "fauna", "favor", "feast",
    "fecal", "feign", "felon", "femme", "femur",
    "fence", "feral", "ferry", "fetal", "fetch",
    "fetid", "fetus", "fever", "fewer", "fiber",
    "ficus", "field", "fiend", "fiery", "fifth",
    "fifty", "fight", "filer", "filet", "filly",
    "filmy", "filth", "final", "finch", "finer",
    "first", "fishy", "fixer", "fizzy", "fjord",
    "flack", "flail", "flair", "flake", "flaky",
    "flame", "flank", "flare", "flash", "flask",
    "fleck", "fleet", "flesh", "flick", "flier",
    "fling", "flint", "flirt", "float", "flock",
    "flood", "floor", "flora", "floss", "flour",
    "flout", "flown", "fluff", "fluid", "fluke",
    "flume", "flung", "flunk", "flush", "flute",
    "flyer", "foamy", "focal", "focus", "foggy",
    "foist", "folio", "folly", "foray", "force",
    "forge", "forgo", "forte", "forth", "forty",
    "forum", "found", "foyer", "frail", "frame",
    "frank", "fraud", "freak", "freed", "freer",
    "fresh", "friar", "fried", "frill", "frisk",
    "fritz", "frock", "frond", "front", "frost",
    "froth", "frown", "froze", "fruit", "fryer",
    "fudge", "fugue", "fully", "fungi", "funky",
    "funny", "furor", "furry", "fussy", "fuzzy",
    "gable", "gaffe", "gaily", "gamer", "gamma",
    "gamut", "gassy", "gaudy", "gauge", "gaunt",
    "gauze", "gavel", "gawky", "gayer", "gayly",
    "gazer", "gecko", "geeky", "geese", "genie",
    "genre", "genus", "ghost", "ghoul", "giant",
    "giddy", "gipsy", "girly", "girth", "given",
    "giver", "glade", "gland", "glare", "glass",
    "glaze", "gleam", "glean", "glide", "glint",
    "gloat", "globe", "gloom", "glory", "gloss",
    "glove", "glyph", "gnash", "gnome", "godly",
    "going", "golem", "golly", "goner", "goody",
    "gooey", "goofy", "goose", "gorge", "gouge",
    "gourd", "gouty", "grace", "grade", "graft",
    "grail", "grain", "grand", "grant", "grape",
    "graph", "grasp", "grass", "grate", "grave",
    "gravy", "graze", "great", "greed", "greek",
    "green", "greet", "grief", "grill", "grime",
    "grimy", "grind", "gripe", "groan", "groin",
    "groom", "grope", "gross", "group", "grout",
    "grove", "growl", "grown", "gruel", "gruff",
    "grunt", "guard", "guava", "guess", "guest",
    "guide", "guild", "guile", "guilt", "guise",
    "gulch", "gully", "gumbo", "gummy", "guppy",
    "gusto", "gusty", "gypsy", "habit", "hairy",
    "halve", "handy", "haply", "happy", "hardy",
    "harem", "harpy", "harry", "harsh", "haste",
    "hasty", "hatch", "hater", "haunt", "haute",
    "haven", "havoc", "hazel", "heady", "heard",
    "heart", "heath", "heave", "heavy", "hedge",
    "hefty", "heist", "helix", "hello", "hence",
    "heron", "hilly", "hinge", "hippo", "hippy",
    "hitch", "hoard", "hoary", "hobby", "hocus",
    "hoist", "holly", "homer", "honey", "honor",
    "horde", "horny", "horse", "hotel", "hotly",
    "hound", "house", "hovel", "hover", "howdy",
    "human", "humid", "humor", "humph", "humus",
    "hunch", "hunky", "hurry", "husky", "hussy",
    "hutch", "hydro", "hyena", "hyper", "icily",
    "icing", "ideal", "idiom", "idiot", "idler",
    "idyll", "igloo", "iliac", "image", "imbue",
    "impel", "imply", "inane", "inbox", "incur",
    "index", "inept", "inert", "infer", "ingot",
    "inlay", "inlet", "inner", "input", "inter",
    "inure", "ionic", "irate", "irony", "islet",
    "issue", "itchy", "ivory", "jaunt", "jazzy",
    "jelly", "jerky", "jetty", "jewel", "jiffy",
    "joint", "joist", "joker", "jolly", "joule",
    "joust", "judge", "juice", "juicy", "jumbo",
    "jumpy", "junta", "junto", "juror", "kappa",
    "karma", "kayak", "kebab", "khaki", "kinky",
    "kiosk", "kitty", "knack", "knave", "knead",
    "kneed", "kneel", "knelt", "knife", "knock",
    "knoll", "known", "koala", "krill", "label",
    "labor", "laden", "ladle", "lager", "lance",
    "lanky", "lapel", "lapse", "large", "larva",
    "laser", "lasso", "latch", "later", "lathe",
    "latte", "laugh", "layer", "leach", "leafy",
    "leaky", "leant", "leapt", "learn", "lease",
    "leash", "least", "leave", "ledge", "leech",
    "leery", "lefty", "legal", "leggy", "lemon",
    "lemur", "leper", "levee", "level", "lever",
    "libel", "liege", "light", "liken", "lilac",
    "limbo", "limit", "linen", "liner", "lingo",
    "links", "lipid", "lithe", "liver", "livid",
    "llama", "loamy", "loath", "lobby", "local",
    "locus", "lodge", "loess", "lofty", "logic",
    "login", "loopy", "loose", "lorry", "loser",
    "lotus", "louse", "lousy", "lover", "lower",
    "lowly", "loyal", "lucid", "lucky", "lucre",
    "lumen", "lumpy", "lunar", "lunch", "lunge",
    "lupus", "lurch", "lurid", "lusty", "lying",
    "lymph", "lyric", "macaw", "macho", "macro",
    "madam", "madly", "mafia", "magic", "magma",
    "maize", "major", "maker", "mambo", "mamma",
    "mammy", "manga", "mange", "mango", "mangy",
    "mania", "manic", "manly", "manna", "manor",
    "maple", "march", "marry", "marsh", "mason",
    "masse", "match", "matey", "mauve", "maxim",
    "maybe", "mayor", "mealy", "meant", "meaty",
    "mecca", "medal", "media", "medic", "melan",
    "melee", "melon", "mercy", "merge", "merit",
    "merry", "messy", "metal", "meter", "metro",
    "micro", "midge", "midst", "might", "milky",
    "mimic", "mince", "miner", "minim", "minor",
    "minty", "minus", "mirth", "miser", "missy",
    "misty", "mixer", "mocha", "modal", "model",
    "modem", "mogul", "moist", "molar", "moldy",
    "money", "month", "moody", "moose", "moped",
    "moral", "moron", "morph", "mossy", "motel",
    "motif", "motor", "motto", "moult", "mound",
    "mount", "mourn", "mouse", "mouth", "mover",
    "movie", "mower", "mucky", "mucus", "muddy",
    "mulch", "multi", "mummy", "munch", "mural",
    "murky", "mushy", "music", "musky", "musty",
    "myrrh", "nadir", "naive", "naked", "nanny",
    "nasal", "nasty", "natal", "natty", "naval",
    "navel", "needs", "needy", "neigh", "nerdy",
    "nerve", "never", "newby", "newer", "newly",
    "nicer", "niche", "niece", "night", "ninja",
    "ninny", "ninth", "noble", "nobly", "noise",
    "noisy", "nomad", "noose", "north", "nosey",
    "notch", "novel", "nudge", "nurse", "nutty",
    "nylon", "nymph", "oaken", "oasis", "obese",
    "occur", "ocean", "ocher", "octal", "octet",
    "odder", "oddly", "offal", "offer", "often",
    "olden", "older", "olive", "ombre", "omega",
    "onion", "onset", "opera", "opine", "opium",
    "optic", "orbit", "order", "organ", "other",
    "otter", "ought", "ounce", "outdo", "outer",
    "outgo", "ovary", "ovate", "overt", "ovine",
    "ovoid", "owing", "owner", "oxide", "ozone",
    "paddy", "pagan", "paint", "paler", "palsy",
    "panel", "panic", "pansy", "pants", "papal",
    "paper", "parer", "parka", "parry", "parse",
    "party", "pasta", "paste", "pasty", "patch",
    "patio", "patsy", "patty", "pause", "payee",
    "peace", "peach", "pearl", "pecan", "pedal",
    "penal", "pence", "penne", "penny", "perch",
    "peril", "perky", "pesky", "pesto", "petal",
    "petty", "phase", "phone", "phony", "photo",
    "piano", "picky", "piece", "piety", "piggy",
    "pilot", "pinch", "piney", "pinky", "pinto",
    "pious", "piper", "pique", "pitch", "pithy",
    "pivot", "pixel", "pixie", "pizza", "place",
    "plaid", "plain", "plait", "plane", "plank",
    "plant", "plate", "plaza", "plead", "pleat",
    "plied", "plier", "pluck", "plumb", "plume",
    "plump", "plunk", "plush", "pocus", "poesy",
    "point", "poise", "poker", "polar", "polka",
    "polyp", "pooch", "poppy", "porch", "poser",
    "posit", "posse", "pouch", "pound", "pouty",
    "power", "prank", "prate", "prawn", "preen",
    "press", "price", "prick", "pride", "pried",
    "prime", "primo", "primp", "print", "prior",
    "prism", "privy", "prize", "probe", "prone",
    "prong", "proof", "prose", "proud", "prove",
    "prowl", "proxy", "prude", "prune", "psalm",
    "pubic", "pudgy", "puffy", "pulpy", "pulse",
    "punch", "pupil", "puppy", "puree", "purer",
    "purge", "purse", "pushy", "putty", "pygmy",
    "quack", "quaff", "quail", "quake", "qualm",
    "quark", "quart", "quash", "quasi", "queen",
    "queer", "quell", "query", "quest", "queue",
    "quick", "quiet", "quill", "quilt", "quire",
    "quirk", "quite", "quota", "quote", "quoth",
    "rabbi", "rabid", "racer", "radar", "radii",
    "radio", "radon", "rainy", "raise", "rajah",
    "rally", "ralph", "ramen", "ranch", "randy",
    "range", "rapid", "rarer", "raspy", "ratio",
    "ratty", "raven", "rayon", "razor", "reach",
    "react", "ready", "realm", "rearm", "rebar",
    "rebel", "rebus", "rebut", "recap", "recur",
    "recut", "reedy", "refer", "refit", "regal",
    "rehab", "reign", "relax", "relay", "relic",
    "remit", "renal", "renew", "repay", "repel",
    "reply", "rerun", "reset", "resin", "retch",
    "retro", "retry", "reuse", "revel", "revue",
    "rhino", "rhyme", "rider", "ridge", "rifle",
    "right", "rigid", "rigor", "rinse", "ripen",
    "riper", "riple", "risen", "riser", "risky",
    "rival", "river", "rivet", "roach", "roast",
    "robin", "robot", "rocky", "rodeo", "roger",
    "rogue", "roomy", "roost", "rosin", "rotor",
    "rouge", "rough", "round", "rouse", "roust",
    "route", "rover", "rowdy", "rower", "royal",
    "ruddy", "ruder", "rugby", "ruler", "rumba",
    "rumor", "rupee", "rural", "rusty", "sable",
    "sadly", "safer", "saint", "salad", "sally",
    "salon", "salsa", "salty", "salve", "salvo",
    "sandy", "saner", "sappy", "sassy", "satin",
    "satyr", "sauce", "saucy", "sauna", "saute",
    "savor", "savoy", "savvy", "scald", "scale",
    "scalp", "scaly", "scamp", "scant", "scare",
    "scarf", "scary", "scene", "scent", "scion",
    "scoff", "scold", "scone", "scoop", "scope",
    "score", "scorn", "scour", "scout", "scowl",
    "scram", "scrap", "scree", "screw", "scrub",
    "scrum", "scuba", "sedan", "seedy", "segue",
    "seize", "semen", "sense", "sepia", "serif",
    "serum", "serve", "setup", "seven", "sever",
    "sewer", "shack", "shade", "shady", "shaft",
    "shake", "shaky", "shale", "shall", "shalt",
    "shame", "shank", "shape", "shard", "share",
    "shark", "sharp", "shave", "shawl", "sheaf",
    "shear", "sheen", "sheep", "sheer", "sheet",
    "sheik", "shelf", "shell", "shied", "shift",
    "shine", "shiny", "shire", "shirk", "shirt",
    "shoal", "shock", "shone", "shook", "shoot",
    "shore", "shorn", "short", "shout", "shove",
    "shown", "showy", "shred", "shrew", "shrub",
    "shrug", "shuck", "shunt", "shush", "shyly",
    "siege", "sieve", "sight", "sigma", "silky",
    "silly", "since", "sinch", "sinew", "singe",
    "siren", "sissy", "sixth", "sixty", "skate",
    "skier", "skiff", "skill", "skimp", "skirt",
    "skulk", "skull", "skunk", "slack", "slain",
    "slang", "slant", "slash", "slate", "slave",
    "sleek", "sleep", "sleet", "slept", "slice",
    "slick", "slide", "slime", "slimy", "sling",
    "slink", "sloop", "slope", "slosh", "sloth",
    "slump", "slung", "slunk", "slurp", "slush",
    "slyly", "smack", "small", "smart", "smash",
    "smear", "smell", "smelt", "smile", "smirk",
    "smite", "smith", "smock", "smoke", "smoky",
    "smote", "snack", "snail", "snake", "snaky",
    "snare", "snarl", "sneak", "sneer", "snide",
    "sniff", "snipe", "snoop", "snore", "snort",
    "snout", "snowy", "snuck", "snuff", "soapy",
    "sober", "soggy", "solar", "solid", "solve",
    "sonar", "sonic", "sonny", "sooth", "sooty",
    "sopor", "sorry", "sound", "south", "sower",
    "space", "spade", "spank", "spare", "spark",
    "spasm", "spawn", "speak", "spear", "speck",
    "speed", "spell", "spelt", "spend", "spent",
    "sperm", "spice", "spicy", "spied", "spiel",
    "spike", "spiky", "spill", "spilt", "spine",
    "spiny", "spire", "spite", "splat", "split",
    "spoil", "spoke", "spoof", "spook", "spool",
    "spoon", "spore", "sport", "spout", "spray",
    "spree", "sprig", "spunk", "spurn", "spurt",
    "squad", "squat", "squib", "stack", "staff",
    "stage", "staid", "stain", "stair", "stake",
    "stale", "stalk", "stall", "stamp", "stand",
    "stank", "stare", "stark", "start", "stash",
    "state", "stave", "stead", "steak", "steal",
    "steam", "steed", "steel", "steep", "steer",
    "stein", "stern", "stick", "stiff", "stile",
    "still", "stilt", "sting", "stink", "stint",
    "stoat", "stock", "stoic", "stoke", "stole",
    "stomp", "stone", "stony", "stood", "stool",
    "stoop", "store", "stork", "storm", "story",
    "stout", "stove", "strap", "straw", "stray",
    "strew", "strip", "strut", "stuck", "study",
    "stuff", "stump", "stung", "stunk", "stunt",
    "style", "suave", "sugar", "suing", "suite",
    "sulky", "sully", "sumac", "sunny", "super",
    "surer", "surge", "surly", "sushi", "swami",
    "swamp", "swarm", "swash", "swath", "swear",
    "sweat", "sweep", "sweet", "swell", "swept",
    "swift", "swill", "swine", "swing", "swipe",
    "swirl", "swish", "swoon", "swoop", "sword",
    "swore", "sworn", "swung", "synod", "syrup",
    "tabby", "table", "taboo", "tacit", "tacky",
    "taffy", "taint", "taken", "taker", "tally",
    "talon", "tamer", "tango", "tangy", "taper",
    "tapir", "tardy", "tarot", "tarry", "taste",
    "tasty", "tatty", "taunt", "tawny", "teach",
    "teary", "tease", "teddy", "teeth", "tempo",
    "tempt", "tenet", "tenor", "tense", "tenth",
    "tepee", "tepid", "terra", "terse", "testy",
    "thank", "theft", "their", "theme", "there",
    "these", "theta", "thick", "thief", "thigh",
    "thine", "thing", "think", "third", "thong",
    "thorn", "those", "three", "threw", "throb",
    "throw", "thrum", "thumb", "thump", "thyme",
    "tiara", "tibia", "tidal", "tiger", "tight",
    "tilde", "timer", "timid", "tinge", "tipsy",
    "tired", "titan", "tithe", "title", "toast",
    "today", "toddy", "token", "tonal", "tonga",
    "tonic", "tooth", "topaz", "topic", "topsy",
    "toran", "torch", "torso", "torus", "total",
    "totem", "touch", "tough", "towel", "tower",
    "toxic", "toxin", "trace", "track", "tract",
    "trade", "trail", "train", "trait", "tramp",
    "trash", "trawl", "tread", "treat", "trend",
    "triad", "trial", "tribe", "trice", "trick",
    "tried", "tripe", "trite", "troll", "troop",
    "trope", "trout", "trove", "truce", "truck",
    "truer", "truly", "trump", "trunk", "truss",
    "trust", "truth", "tryst", "tubal", "tuber",
    "tulip", "tulle", "tumor", "tuner", "tunic",
    "tuple", "turbo", "turvy", "tutor", "twain",
    "twang", "tweak", "tweed", "tweet", "twice",
    "twill", "twine", "twirl", "twirp", "twist",
    "twixt", "tying", "udder", "ulcer", "ultra",
    "umbra", "uncle", "uncut", "under", "undid",
    "undue", "unfed", "unfit", "unify", "union",
    "unite", "unity", "unlit", "unmet", "unset",
    "untie", "until", "unwed", "unzip", "upend",
    "upper", "upset", "urban", "urine", "usage",
    "usher", "using", "usual", "usurp", "utile",
    "utter", "vague", "valet", "valid", "valor",
    "value", "valve", "vapid", "vapor", "vault",
    "vaunt", "vegan", "venom", "venue", "verge",
    "verse", "verso", "verve", "vetch", "vicar",
    "video", "vigil", "vigor", "vilan", "viler",
    "villa", "vinyl", "viola", "viper", "viral",
    "virus", "visit", "visor", "vista", "vital",
    "vivid", "vixen", "vocal", "vodka", "vogue",
    "voice", "voila", "vomit", "voter", "vouch",
    "vowel", "vying", "wacky", "wafer", "wager",
    "wagon", "waist", "waive", "waltz", "warty",
    "waste", "watch", "water", "waver", "waxen",
    "weary", "weave", "wedge", "weedy", "weigh",
    "weird", "welch", "welsh", "whack", "whale",
    "wharf", "wheat", "wheel", "whelp", "where",
    "which", "whiff", "while", "whine", "whiny",
    "whirl", "whirr", "whisk", "white", "whole",
    "whoop", "whose", "widen", "wider", "widow",
    "width", "wield", "wight", "wiley", "willy",
    "wimpy", "wince", "winch", "windy", "wiper",
    "wiser", "wispy", "witch", "witty", "woken",
    "woman", "women", "woody", "wooer", "wooly",
    "woozy", "wordy", "world", "worry", "worse",
    "worst", "worth", "would", "wound", "woven",
    "wrack", "wrapt", "wrath", "wreak", "wreck",
    "wrest", "wring", "wrist", "write", "wrong",
    "wrote", "wrung", "wryly", "xenon", "yacht",
    "yearn", "yeast", "yield", "young", "youth",
    "zebra", "zesty", "zippy", "zonal",
}

SECRET_WORDS_LIST = sorted(SECRET_WORDS_SET)

# Plural nouns and present tense third person verbs
_PLURALS_AND_THIRD_PERSON_SET = {
    "acres", "arabs", "areas", "arias", "ashes",
    "asses", "atoms", "aunts", "ayres", "babes",
    "backs", "balls", "bands", "bangs", "banks",
    "barbs", "barks", "barns", "baths", "beads",
    "beaks", "beams", "beans", "bears", "beats",
    "beets", "bells", "belts", "bends", "biles",
    "bills", "binds", "birds", "bites", "blows",
    "boats", "bolts", "bombs", "bonds", "bones",
    "books", "boots", "bores", "bowls", "boxes",
    "brays", "brims", "bucks", "bulbs", "bulls",
    "bumps", "bunks", "burns", "burrs", "busts",
    "cages", "cakes", "calls", "camps", "capes",
    "cards", "cares", "carts", "cases", "casts",
    "cauls", "caves", "cells", "cents", "chaps",
    "chins", "chips", "chops", "chums", "clams",
    "claps", "claws", "cloys", "clubs", "coals",
    "coats", "cocks", "codes", "coins", "colds",
    "colts", "combs", "comes", "cones", "cooks",
    "cools", "coons", "coots", "cords", "corks",
    "costs", "coves", "crabs", "crags", "crews",
    "cries", "crops", "crows", "cuffs", "cures",
    "curls", "dames", "damps", "dares", "darts",
    "dates", "dawns", "dears", "debts", "decks",
    "deeds", "deems", "dikes", "dimes", "dines",
    "discs", "disks", "dives", "docks", "doers",
    "dolls", "doors", "doses", "dotes", "doves",
    "downs", "drags", "draws", "dregs", "dries",
    "drops", "drugs", "drums", "ducks", "duets",
    "dukes", "dumps", "dunes", "eaves", "edges",
    "evens", "evils", "exits", "faces", "facts",
    "fails", "fairs", "falls", "fangs", "farms",
    "fasts", "fears", "feats", "feeds", "feels",
    "fells", "felts", "ferns", "files", "fills",
    "films", "finds", "fires", "fists", "flags",
    "flats", "flaws", "flies", "flits", "flops",
    "flows", "foals", "folds", "folks", "foods",
    "fools", "forks", "forms", "forts", "fours",
    "fowls", "foxes", "fries", "frogs", "funds",
    "gains", "gales", "galls", "games", "gates",
    "germs", "gifts", "gills", "girls", "gives",
    "glows", "gnaws", "goads", "goals", "goats",
    "gongs", "goods", "gowns", "grays", "grows",
    "gulls", "gusts", "hairs", "halls", "hands",
    "hangs", "hares", "harps", "harts", "hates",
    "hawks", "heads", "heals", "heaps", "hears",
    "heels", "heirs", "helps", "herbs", "herds",
    "hicks", "hides", "hills", "hilts", "hints",
    "hives", "hocks", "holds", "holes", "homes",
    "hoods", "hoofs", "hooks", "hoops", "hopes",
    "horns", "hosts", "hours", "howls", "hunts",
    "hurts", "husks", "hymns", "ideas", "idols",
    "irons", "isles", "items", "ivies", "jacks",
    "jails", "jeers", "jests", "joins", "jokes",
    "jukes", "jumps", "junks", "keeps", "kicks",
    "kills", "kinds", "kings", "knees", "knobs",
    "knots", "knows", "laces", "lacks", "lakes",
    "lambs", "lamps", "lands", "lanes", "lasts",
    "lawns", "leads", "leans", "leaps", "lends",
    "liars", "licks", "lifts", "likes", "limbs",
    "lines", "lions", "lives", "loads", "lobes",
    "locks", "loins", "longs", "looks", "looms",
    "loops", "loses", "loves", "lulls", "lumps",
    "lungs", "lusts", "maids", "mails", "makes",
    "males", "marks", "masks", "masts", "meals",
    "means", "meets", "miles", "mills", "minds",
    "mines", "mists", "mites", "mixes", "moans",
    "modes", "moles", "moods", "moons", "moths",
    "moves", "mules", "muses", "nails", "names",
    "necks", "nests", "newts", "nooks", "noses",
    "notes", "oaths", "odors", "opens", "pages",
    "pails", "pains", "pairs", "palms", "panes",
    "pangs", "parks", "parts", "paths", "peaks",
    "pears", "peeps", "peers", "peons", "pikes",
    "piles", "pills", "pines", "pints", "pipes",
    "plans", "plays", "plots", "plows", "plums",
    "poems", "poets", "poles", "polls", "ponds",
    "pools", "popes", "ports", "posts", "preys",
    "pulls", "pumps", "quits", "races", "racks",
    "rages", "raids", "rails", "rains", "ranks",
    "rates", "reads", "reams", "reeds", "reefs",
    "reins", "rents", "rests", "rides", "rills",
    "rings", "riots", "rises", "risks", "rites",
    "roads", "roars", "robes", "rocks", "rolls",
    "roofs", "rooms", "roots", "ropes", "roses",
    "ruins", "rules", "runts", "sages", "sails",
    "sakes", "salts", "sands", "saves", "scars",
    "seals", "seams", "seats", "sects", "seeds",
    "seeks", "seems", "seers", "sells", "sends",
    "sexes", "sheds", "shins", "ships", "shoes",
    "shops", "shots", "shows", "shuts", "sides",
    "sighs", "signs", "silks", "sings", "sinks",
    "sites", "sizes", "skies", "skins", "slays",
    "slips", "slits", "slugs", "slums", "snips",
    "snows", "soars", "socks", "soils", "soles",
    "solos", "songs", "sorts", "souls", "spans",
    "spars", "spats", "spews", "spies", "spots",
    "stabs", "stags", "stars", "stays", "stems",
    "steps", "stirs", "stops", "stuns", "suits",
    "sulks", "sways", "swims", "tails", "takes",
    "tales", "talks", "tanks", "tares", "tasks",
    "taxes", "teams", "tears", "teats", "teens",
    "tells", "tends", "tents", "terms", "texts",
    "thins", "tides", "tiles", "times", "tints",
    "tires", "toads", "toils", "tombs", "tomes",
    "tones", "tongs", "tools", "towns", "traps",
    "trays", "trees", "tries", "trips", "tubes",
    "tufts", "tunes", "turns", "twigs", "twins",
    "twits", "types", "units", "urges", "vanes",
    "vases", "veils", "veins", "vests", "vices",
    "views", "vines", "viols", "voids", "votes",
    "wages", "waits", "wakes", "walks", "walls",
    "wands", "wanes", "wants", "wares", "warms",
    "warns", "wasps", "waves", "wears", "weeds",
    "weeks", "wells", "whims", "wilds", "wiles",
    "wills", "winds", "wines", "wings", "winks",
    "wires", "wives", "woods", "words", "works",
    "worms", "wraps", "wrens", "yards", "years",
    "yells", "yours", "zones", "zulus",
}

# Past tense verbs
_PAST_TENSE_SET = {
    "ached", "acted", "added", "aided", "ailed",
    "aimed", "armed", "asked", "baked", "based",
    "bated", "blown", "bored", "bowed", "cared",
    "cited", "cured", "dared", "dated", "dazed",
    "dined", "dived", "doted", "dozed", "eased",
    "ebbed", "edged", "egged", "ended", "erred",
    "faced", "faded", "fared", "fated", "filed",
    "fired", "fixed", "gaped", "gazed", "glued",
    "hated", "hired", "hoped", "jawed", "joyed",
    "keyed", "laced", "liked", "lined", "lived",
    "loved", "mated", "meted", "mined", "mixed",
    "moved", "mused", "named", "nosed", "noted",
    "oiled", "owned", "paced", "paved", "piled",
    "pined", "piped", "raced", "raged", "raved",
    "riled", "ruled", "sated", "saved", "sawed",
    "sewed", "sided", "sized", "sowed", "tamed",
    "taxed", "tiled", "timed", "toned", "toyed",
    "urged", "vexed", "voted", "vowed", "waged",
    "waked", "waned", "waved", "waxed", "wiped",
    "wired", "wroth", "yoked",
}

# Prefixes and suffixes
_PREFIXES_AND_SUFFIXES_SET = {
    "infra", "intra", "intro",
}

# British and dated spellings
_DATED_SPELLINGS_SET = {
    "aeons", "blest", "canst", "coney", "crape",
    "didst", "dieth", "doest", "doeth", "drury",
    "durst", "fianc", "fibre", "fower", "goest",
    "goeth", "gwine", "hadst", "ledst", "lhama",
    "liest", "lieth", "mater", "mould", "ochre",
    "odour", "pater", "saith", "seest", "seeth",
    "shews", "spake", "stowe", "sware", "tyres",
    "vesta", "whoso",
}

# Location names
_LOCATIONS_SET = {
    "abana", "ablom", "agosh", "aiath", "alamo",
    "andes", "antum", "arpad", "babel", "bronx",
    "cairo", "calno", "chile", "china", "congo",
    "crecy", "cuban", "cuney", "egypt", "essex",
    "gebim", "genoa", "hades", "horeb", "idaho",
    "india", "irish", "italy", "japan", "judea",
    "laish", "latin", "maine", "manti", "medes",
    "melek", "milan", "minon", "mocum", "nahom",
    "nubia", "ogath", "omner", "ophir", "padua",
    "paris", "rahab", "ramah", "rhine", "roman",
    "salem", "sebus", "seine", "sheba", "shurr",
    "sidom", "sidon", "sinai", "sinim", "siron",
    "sodom", "spain", "swiss", "syria", "tacna",
    "texas", "tibet", "tokyo", "vinci", "volga",
    "wales", "yumas", "zerin",
}

# Person names
_NAMES_SET = {
    "aaron", "abish", "adair", "adams", "addie",
    "adnah", "adolf", "akish", "alice", "allen",
    "amgid", "ammah", "ammon", "annie", "anton",
    "arden", "avery", "bates", "becky", "beebe",
    "beesy", "bella", "betsy", "betty", "blair",
    "blake", "bowen", "brady", "brent", "bruce",
    "buell", "burke", "byron", "caleb", "carlo",
    "casey", "cecil", "celia", "chang", "cheng",
    "chuan", "clara", "clark", "cohor", "corom",
    "cupid", "cyrel", "cyrus", "danby", "danny",
    "dante", "david", "davis", "deane", "demas",
    "diana", "diego", "doane", "eddie", "edith",
    "edwin", "elgin", "elias", "elisa", "eliza",
    "ellen", "elsie", "elvit", "emily", "emory",
    "emron", "enoch", "eolus", "esrom", "ethel",
    "ethem", "ewing", "ezias", "giang", "gould",
    "gregg", "guido", "hagar", "heber", "helam",
    "helem", "helen", "henry", "herod", "higgs",
    "himni", "hiram", "hoang", "hogan", "huber",
    "hyrum", "irwin", "isaac", "jacob", "jacom",
    "james", "janey", "jared", "jarom", "jenks",
    "jenny", "jesse", "jesus", "jimmy", "jonah",
    "jonas", "jones", "josey", "josie", "judah",
    "judas", "jules", "julia", "julie", "katie",
    "kelly", "kirby", "korah", "kumen", "kwang",
    "laban", "laius", "lamah", "laman", "larue",
    "laura", "lenox", "lewis", "liang", "limhi",
    "logan", "lopez", "louis", "lucas", "lucia",
    "lucin", "luram", "lydia", "mabel", "macey",
    "mahah", "maher", "marco", "mardi", "maria",
    "marie", "maude", "meigs", "micah", "molly",
    "monte", "moore", "moses", "mulek", "nancy",
    "naomi", "nehor", "nephi", "pagag", "paine",
    "paley", "payne", "peale", "pedro", "pekah",
    "peleg", "percy", "peter", "plato", "poore",
    "ramus", "regis", "remus", "rezin", "riley",
    "rodin", "romeo", "santa", "sarah", "satan",
    "scott", "selma", "shule", "simon", "sousa",
    "spode", "susan", "terry", "titus", "tommy",
    "tyson", "unger", "upton", "uriah", "venus",
    "wally", "walsh", "weber", "yates", "zenos",
    "zeram", "zoram",
}

# Words from other languages
_FOREIGN_WORDS_SET = {
    "adieu", "amnor", "ephah", "ezrom", "honan",
    "hsien", "mitre", "monde", "moulu", "selah",
    "senum", "sheng", "sheum", "vliet", "wutai",
    "yamen",
}

_ACRONYMS_SET = {
    "ascii", "ebook", "https", "pglaf",
}

_ROMAN_NUMERALS_SET = {
    "xviii", "xxiii", "xxvii", "xxxii", "xxxiv",
    "xxxvi",
}

_OTHER_WORDS_SET = {
    "april", "banns", "barer", "barre", "befog",
    "brung", "caird", "colly", "derry", "finis",
    "fitly", "gatty", "gooch", "hubby", "kodak",
    "lynch", "manse", "negro", "penis", "pimas",
    "pussy", "serge", "skoal", "surah", "timey",
    "vulva", "whore",
}


def union_all(sets_list):
    new_set = set()
    for curr_set in sets_list:
        new_set.update(curr_set)
    return new_set

ALLOWED_WORDS_SET = union_all([SECRET_WORDS_SET,
        _PLURALS_AND_THIRD_PERSON_SET, _PAST_TENSE_SET, _OTHER_WORDS_SET])

# A set of all known words that is used by this program
# when searching text for new five-letter words.
_KNOWN_WORDS_SET = union_all([SECRET_WORDS_SET, _PLURALS_AND_THIRD_PERSON_SET,
        _PAST_TENSE_SET, _PREFIXES_AND_SUFFIXES_SET, _DATED_SPELLINGS_SET,
        _LOCATIONS_SET, _NAMES_SET, _FOREIGN_WORDS_SET,
        _ACRONYMS_SET, _ROMAN_NUMERALS_SET, _OTHER_WORDS_SET])


def extract_unknown_words():
    #filename = input("Name of file that contains text: ")
    filename = "book.txt"
    with open(filename, "rt", encoding="utf8") as text_file:
        text1 = text_file.read().lower()

    # Keep only space characters and English letters. Remove all other
    # characters.
    text2 = re.sub(r"[^\sa-z]+", " ", text1)

    # Keep only five letter words. Remove all other words.
    text3 = re.sub(r"\b([a-z]{1,4}|[a-z]{6,})\b", "", text2)

    # Replace all whitespace characters with a space.
    text4 = re.sub(r"\s+", " ", text3)

    words_set = set(text4.split())
    new_words_set = words_set - _KNOWN_WORDS_SET

    for word in sorted(new_words_set):
        print(word)


def print_sorted_words():
    ALL_SETS = [
        ("SECRET_WORDS_SET", SECRET_WORDS_SET),
        ("_PLURALS_AND_THIRD_PERSON_SET", _PLURALS_AND_THIRD_PERSON_SET),
        ("_PAST_TENSE_SET", _PAST_TENSE_SET),
        ("_PREFIXES_AND_SUFFIXES_SET", _PREFIXES_AND_SUFFIXES_SET),
        ("_DATED_SPELLINGS_SET", _DATED_SPELLINGS_SET),
        ("_LOCATIONS_SET", _LOCATIONS_SET),
        ("_NAMES_SET", _NAMES_SET),
        ("_FOREIGN_WORDS_SET", _FOREIGN_WORDS_SET),
        ("_ACRONYMS_SET", _ACRONYMS_SET),
        ("_ROMAN_NUMERALS_SET", _ROMAN_NUMERALS_SET),
        ("_OTHER_WORDS_SET", _OTHER_WORDS_SET),
    ]
    for set_name, word_set in ALL_SETS:
        print_words_set(set_name, word_set)


def print_words_set(set_name, words_set):
    per_line = 5
    i = per_line
    sep = "    "
    print(set_name, "= {")
    for word in sorted(words_set):
        print(f'{sep}"{word}",', end="")
        i -= 1
        if i == 0:
            sep = "\n    "
            i = per_line
        else:
            sep = " "
    print()
    print("}")
    print()


# Call a function to start this program.
if __name__ == "__main__":
    extract_unknown_words()
    #print_sorted_words()
